### ISSUE TITLE
Add IV to the pokemon catch messages

### ISSUE THREAD

**Issue by Vexy1** [poketwo/poketwo#392] opened 2022-03-13 16:14 UTC
Ok so like whenever i run 10-12 incense i dont have time to do p!i 0 and check if its good stats nor is it easy to check when ur done with the incenses it takes time, so i suggest adding the caught pokemon's IV along side its level

**Comment by Cam2930** [comment] 2022-03-13 16:18
I think it was rejected before

**Comment by TheWildEye** [comment] 2022-03-13 16:49
I support this issue! cuz we can't check every pokemon during incense. We have to pay 10k Pc so I don't think there is any reason to miss any pokemon just in sake of checking it's iv first! Kindly Consider.

**Comment by Cam2930** [comment] 2022-03-13 16:57
But you can check it after the incense is done. Just after the incense is done cause when you do p!I L it will go to the last one you caught then if you press left you can see the others you caught with the iv in it

**Comment by TheWildEye** [comment] 2022-03-13 17:02
Time is money my friend. 
It's better to spend that time in making profit in auctions and market rather than just scrolling left and checking all the pokemons.Its better to stay together with an issue! United We Stand, Divided We Fall.

**Comment by Cam2930** [comment] 2022-03-13 17:06
It's been rejected to avoid unwanted dms

**Comment by WitherredAway** [comment] 2022-03-16 20:59
Duplicate of #271, not quite sure what decision was made regarding this.

**Comment by WitherredAway** [comment] 2022-03-19 07:31
Duplicate of #271

**Closed by WitherredAway** 2022-03-19 07:31 UTC
Labels: duplicate, enhancement
