### ISSUE TITLE
New pokemon

### ISSUE THREAD

**Issue by Jynx69** [poketwo/poketwo#204] opened 2021-05-14 17:21 UTC
hello poketwo Creators I was wondering if we would ever get the Sword and shield pokemon in Poketwo like Zacian and zamazenta and galar forms I don't think gmax should be a thing though it would be too broken I hope I will see this in the future

**Comment by oliver-ni** [comment] 2021-05-14 17:51
Duplicate of #69

**Closed by oliver-ni** 2021-05-14 17:51 UTC
Labels: enhancement
