### ISSUE TITLE
Reset Command 

### ISSUE THREAD

**Issue by Shizuka-minamoto** [poketwo/poketwo#387] opened 2022-03-11 11:53 UTC
Add a command to reset all the poketwo data including dex, coins and quests. Those players who wants to quit can use it and prevent themselves from the addiction of the bot.
Also give suspended users a second chance to use the bot again by resetting all their data and start as a beginner. There are many users who were suspended for suspicious activity and association with autocachers unknowingly. There is literally nothing we can do to check who is autocatching and who isn't and the worst part is that their appeals gets rejected due to lack of transparency between mods and accused users. Giving them a second chance will be fair for them.

**Comment by WitherredAway** [comment] 2022-03-17 00:16
Kinda half duplicate of #383. Please refer to [the command by Oliver](https://github.com/poketwo/poketwo/issues/383#issuecomment-1061345291) on that issue regarding deletion of your account.

**Comment by Shizuka-minamoto** [comment] 2022-03-18 08:21
everyone cannot email oliver for doing it for them. a command to do it will be reliable for both community and developers.

**Comment by WitherredAway** [comment] 2022-03-18 08:25
You are right, and as oliver stated, this will be taken care of in the future when he's able to prioritize it. For now though, the only way is to email.

**Comment by Renaissance96** [comment] 2022-03-21 04:09
yes they will take care of it in future just like they are taking care of galarian region Pokemon moves since almost a year and just like cross trading policy since 6 months.🤡

**Comment by WitherredAway** [comment] 2022-03-21 04:25
This is extremely rude and inconsiderate. Please keep in mind that due to certain circumstances, Poketwo has only one single developer. They've always been the sole developer of the bot. And we have all these awesome features regardless of that. So ungrateful comments like this are super discouraging and uncalled for. They have a life too, and as such it is impossible for them to focus all their time on poketwo. On top of all this, he has a handful of things that take higher priority right now. As you should know, discord is forcing bot developers to completely rewrite their bots to implement slash-commands, this is not an easy task especially for a bot that is as big as poketwo and especially because the discord api library poketwo uses has barely implemented slash-commands - So this is the one thing he's prioritizing about the bot right now. He has an admin team who are currently working on the cross-trading policy, but that's not an easy task either. They all are trying their best, so it would be greatly appreciated if you all could be patient and grateful for what you have. We *are* sorry for the inconvenience, and hope that you understand.

**Comment by fdsmjkfjires** [comment] 2022-03-21 04:38
> This is extremely rude and inconsiderate. Please keep in mind that due to certain circumstances, Poketwo has only one single developer. They've always been the sole developer of the bot. And we have all these awesome features regardless of that. So ungrateful comments like this are super discouraging and uncalled for. They have a life too, and as such it is impossible for them to focus all their time on poketwo. On top of all this, he has a handful of things that take higher priority right now. As you should know, discord is forcing bot developers to completely rewrite their bots to implement slash-commands, this is not an easy task especially for a bot that is as big as poketwo and especially because the discord api library poketwo uses has barely implemented slash-commands - So this is the one thing he's prioritizing about the bot right now. He has an admin team who are currently working on the cross-trading policy, but that's not an easy task either. They all are trying their best, so it would be greatly appreciated if you all could be patient and grateful for what you have. We _are_ sorry for the inconvenience, and hope that you understand.

i agree but then some ppl are like me have been banned for auto catching or assositation but i never recalled using a auto catcher and then i found out my friend was giving me pokemons/pc to keep it with me for sometime and give it back and this was assosiation but then when i appeal it has been 3months nd still not reply

**Comment by WitherredAway** [comment] 2022-03-21 04:40
> i agree but then some ppl are like me have been banned for auto catching or assositation but i never recalled using a auto catcher and then i found out my friend was giving me pokemons/pc to keep it with me for sometime and give it back and this was assosiation but then when i appeal it has been 3months nd still not reply
I'm sorry to here this, please open a ticket in our support server at https://discord.gg/poketwo-support and we'll get you sorted as soon as possible

**Comment by Renaissance96** [comment] 2022-03-21 05:35
> 

they have full time to simp on animes and not to fix bugs?
and also working on ct policy won't take more than a day or two, saying they haven't got time since 6 months is nothing more than a excuse. they might have working on slash command since a month or two but not since a year.

**Comment by Alex-Stafford1** [comment] 2022-03-21 05:43
man saying "awesome features" when they copied it from pokecord bot 😂

**Comment by WitherredAway** [comment] 2022-03-21 05:43
You don't and will never fully know what's going on in a person's life. Saying that they "simp on animes" all the time is extreme levels of rude and insensitive. The developer has done a lot for the community and you cannot ignore that just because something is taking longer than you'd like. I understand your frustration but you have to keep in mind that you will never know what a person's life is like. The developer for the majority of last year was busy with things that are important to their life. Poketwo is not their full-time job and it does not take priority over their life. 

And CT policy is not a simple thing. It is basically a legal issue that they need to come to a consensus about with the entire staff team before writing. You are arguing based on complete and utter assumptions that are very inaccurate. You are not entitled to anything so stop acting that way and try to be considerate.

**Comment by WitherredAway** [comment] 2022-03-21 05:44
> man saying "awesome features" when they copied it from pokecord bot 😂

It is not a pokecord copy, the developer fully wrote this bot on their own even if it may have some similarities. Do not assume things and comment things that you think are true without confirming.

**Comment by Alex-Stafford1** [comment] 2022-03-21 05:49
i have played pokecord for a long time and i know what i am talking about.

**Comment by WitherredAway** [comment] 2022-03-21 05:53
> i have played pokecord for a long time and i know what i am talking about.

I do not disagree with you that there are a lot of similarities between the two but have you taken a look at pokecord's code? Is it the exact same? No it is not, and that's my point. There may be similarities but the code of poketwo is the poketwo developer's hard work and you cannot deny that. Even though there are similarities, at the same time a lot is different about poketwo in comparison so calling it a pokecord copy does not do it justice

**Comment by Alex-Stafford1** [comment] 2022-03-21 05:56
different codes with same features and if you check my comment, you will find i said "awesome features" and not codes. anyways, i don't want to argue about it. Ty!!

**Comment by WitherredAway** [comment] 2022-03-21 06:00
Sorry if my comment came off rude, it's just that it genuinely makes me upset to see the ungratefulness and harsh comments towards someone who has done so much for us :/

**Comment by Shizuka-minamoto** [comment] 2022-03-21 06:04
My issue has changed into a completely different topic. ;-;

**Comment by WitherredAway** [comment] 2022-03-21 06:05
> different codes with same features and if you check my comment, you will find i said "awesome features" and not codes. anyways, i don't want to argue about it. Ty!!

And regarding this, i still think it's inaccurate. Calling the "same features" is wrong, if you've played pokecord for a long time, you'll know that there are a lot of differences between poketwo and pokecord the same way there are similarities

**Comment by WitherredAway** [comment] 2022-03-21 06:17
> My issue has changed into a completely different topic. ;-;

Yeah it's sad honestly

**Comment by fdsmjkfjires** [comment] 2022-03-21 06:54
> > My issue has changed into a completely different topic. ;-;
> 
> Yeah it's sad honestly

ik lol

**Closed** 2022-03-21 19:00 UTC
Labels: enhancement
