### ISSUE TITLE
Add Evolution Commands

### ISSUE THREAD

**Issue by iceicx** [poketwo/poketwo#145] opened 2021-02-09 11:33 UTC
Add commands for searching all the pokemons of the same evolution
Example: --ev eevee
                shows all the eeveelution
                --ev charmander
                shows charmander, charmeleon, & charizard
                --ev blastoise
                shows bulbasaur, wartortle, & blastoise

This could help people that are collecting pokemon's for easier trading and finding pokemons of the same evolution

**Comment by NathNathNathNath** [comment] 2021-02-09 11:36
This is probably not necessary, I think all of the dex entries already have a section specific to evolution. Example:
![image](https://user-images.githubusercontent.com/39986236/107358267-151c1780-6acb-11eb-826c-369f3ca70a33.png)

**Comment by iceicx** [comment] 2021-02-10 02:02
> This is probably not necessary, I think all of the dex entries already have a section specific to evolution. Example:
> ![image](https://user-images.githubusercontent.com/39986236/107358351-2e24c880-6acb-11eb-9cae-efb683eddfc5.png)

Though, this could be a much more quicker way to search for pokemons and or trading.
And you also don't have to dex it to find and check for it.

**Comment by WitherredAway** [comment] 2022-03-16 23:56
Duplicate of #64

**Closed by WitherredAway** 2022-03-16 23:56 UTC
Labels: duplicate
